[project]
name = "community-vk-analysis"
version = "0.1.0"
description = "Анализ сообществ ВКонтакте"
authors = [
    {name = "Anastasia"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "datetime (>=6.0,<7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
